// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDliA3B3vrunmeyfWmlWyFxmErB6DxJ3lk',
    appId: '1:599794633321:web:13e6053814e772dea830f8',
    messagingSenderId: '599794633321',
    projectId: 'test-neflix',
    authDomain: 'test-neflix.firebaseapp.com',
    storageBucket: 'test-neflix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQzyKYAzI6kdsm33kZrLQwbopbCAv8MU',
    appId: '1:599794633321:android:1dbf34ebde58877ea830f8',
    messagingSenderId: '599794633321',
    projectId: 'test-neflix',
    storageBucket: 'test-neflix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQpawS9K6RJXJAzd4N1Zh4HZSQKaNDXrg',
    appId: '1:599794633321:ios:71f3aceb470e88efa830f8',
    messagingSenderId: '599794633321',
    projectId: 'test-neflix',
    storageBucket: 'test-neflix.appspot.com',
    iosClientId: '599794633321-eebbh5dugkroe9rfuthgjuvcic5j8527.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNetflix',
  );
}
